default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: devise1_dev
  username: sa
  password: $wordf1sh
  host: localhost

test:
  <<: *default
  database: devise1_test %>
  username: sa
  password: $wordf1sh
  host: localhost

production:
  <<: *default
  database: devise1_prod