# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15774762ac2c5d3f60466acf39af0dd76f906c437c5b8776eda32cc39efaad4b43638840ae668084a3a03b93dbe57077d002d1f482391909e9c246b9e3a14a43

test:
  secret_key_base: 7afcc1e0833cce30b4ec37f5e2a5da26e12852a3ed67dc5bc8ac602a479de7446c69e51c2b53310287dbc276cc66b7dbeef06f61eedf7b2811a92ad7e35fe7f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
